apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-two-deployment
  labels:
    app: nginx-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-two
  template:
    metadata:
      labels:
        app: nginx-two
    spec:
      containers:
      - name: nginx-two
        image: unkustomized
        ports:
        - containerPort: 8080
