apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: grc-dev-
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  pipelineRef:
    name: grc-dev-day-claim
  params:
  - name: USER_NAME
    value: jkulikau
