apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
    creator: jkulikau
    app: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echoer
        image: quay.io/justinkuli/echo-server:v0.1
        ports:
        - containerPort: 8080
